image:
  liquibase:
    repository: liquibase/liquibase
    tag: latest
    pullPolicy: IfNotPresent

database:
  host: "meghdo-instance.ca9m0486s1c6.us-east-1.rds.amazonaws.com"
  port: "5432"
  name: "meghdo_database"
  username: "dbuser"
  instance: "meghdo-instance"

serviceAccount:
  name: liquibase
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::354918396806:role/rds-access-role
release: "v2.0.0"
rollbackrelease: "v3.0.0"
action: "rollback"
region: "us-east-1"
loglevel: "FINE"


resources:
  liquibase:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

