apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobidentifier }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: liquibase
spec:
  backoffLimit: 5
  template:
    metadata:
        annotations:
          sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: liquibase
          image: "{{ .Values.image.liquibase.repository }}:{{ .Values.image.liquibase.tag }}"
          command: [ "liquibase" ]
          args:
            - "--url=jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}?sslmode=disable"
            - "--changelog-file=master.xml"
            - "{{ .Values.action }}"
          env:
            - name: LIQUIBASE_COMMAND_USERNAME
              value: {{ .Values.database.username }}
            - name: LIQUIBASE_COMMAND_TAG
              value: {{ .Values.release | replace "." "-" }}
            - name: LIQUIBASE_SEARCH_PATH
              value: "./changelog"
            - name: LIQUIBASE_LOG_LEVEL
              value: {{ .Values.loglevel }}
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db_password                
          resources:
            {{- toYaml .Values.resources.liquibase | nindent 12 }}
          volumeMounts:
            - name: changelog
              mountPath: /liquibase/changelog
      volumes:
        - name: changelog
          configMap:
            name: release-{{ .Values.rollbackrelease }}
      restartPolicy: OnFailure
