{{- $secret := lookup "secrets-store.csi.x-k8s.io/v1" "SecretProviderClass" .Release.Namespace "db-password" -}}
  {{- if not $secret }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-password
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: db-password
        objectType: secretsmanager
        objectAlias: db-password
        region: {{ .Values.region }}
  {{- end }}